version: '3.8'

services:
  # PHP Service
  
  php-fpm:
    build:
      context: .
      dockerfile: ./docker/php-fpm/Dockerfile
    container_name: ecomoney_api
    restart: unless-stopped
    tty: true
    volumes:
      - ./app:/var/www/html
    environment:
      - SERVICE_NAME=app
      - SERVICE_TAGS=dev
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
    networks:
      - ecomoney_network

  # Nginx Service
  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-fpm
    networks:
      - ecomoney_network

  # MySQL Service
  mysql:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    container_name: ecomoney_mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./mysql-data:/var/lib/mysql
    networks:
      - ecomoney_network

networks:
  ecomoney_network:
    driver: bridge
