version: '3.8'

services:
  # PHP Service
  php:
    build:
      context: ./docker/php-fpm
      dockerfile: Dockerfile
    container_name: ecomoney_api
    volumes:
      - .:/var/www/html
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
    networks:
      - ecomoney_network

  # Nginx Service
  nginx:
    image: nginx:latest
    container_name: ecomoney_nginx
    ports:
      - "8080:80"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - .:/var/www/html
    depends_on:
      - php
    networks:
      - ecomoney_network

  # MySQL Service
  mysql:
    image: mysql:latest
    container_name: ecomoney_mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./mysql-data:/var/lib/mysql
    networks:
      - ecomoney_network

networks:
  ecomoney_network:
    driver: bridge
